dist: focal

language: cpp

compiler: 
  - clang

sudo: required

before_script:
  - apt-get -qq update

script:
  - mkdir -p build
  - cd build
  - cmake ../ -DGMX_BUILD_OWN_FFTW=ON
  - make
  - make install
