# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/root/gromacs-mo833a;/root/gromacs-mo833a/build_release")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Unspecified;data;development;runtime")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_GENERATOR "TGZ")
set(CPACK_GMX_BUILD_HELP "AUTO")
set(CPACK_IGNORE_FILES "\\.isreposource;\\.git;\\.gitignore;\\.gitattributes;INSTALL-dev;cmake/FindCUDA\\.cmake;cmake/FindCUDA;ccache")
set(CPACK_INSTALLED_DIRECTORIES "/root/gromacs-mo833a;/;/root/gromacs-mo833a/build_release/docs/man;docs/man;/root/gromacs-mo833a/build_release/src/programs/completion;src/programs/completion")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local/gromacs")
set(CPACK_MODULE_PATH "/root/gromacs-mo833a/cmake;/root/gromacs-mo833a/cmake/Platform")
set(CPACK_NSIS_DISPLAY_NAME "gromacs 2020.2-dev")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "gromacs 2020.2-dev")
set(CPACK_OUTPUT_CONFIG_FILE "/root/gromacs-mo833a/build_release/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "gmx-users@gromacs.org")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "GROMACS - a toolkit for high-performance molecular simulation")
set(CPACK_PACKAGE_FILE_NAME "gromacs-2020.2-dev")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "gromacs 2020.2-dev")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "gromacs 2020.2-dev")
set(CPACK_PACKAGE_NAME "gromacs")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "gromacs.org")
set(CPACK_PACKAGE_VERSION "2020.2-dev")
set(CPACK_PACKAGE_VERSION_MAJOR "2020")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "2")
set(CPACK_PROJECT_CONFIG_FILE "/root/gromacs-mo833a/CPackInit.cmake")
set(CPACK_RESOURCE_FILE_LICENSE "/root/gromacs-mo833a/COPYING")
set(CPACK_RESOURCE_FILE_README "/root/gromacs-mo833a/admin/InstallInfo.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/root/gromacs-mo833a/admin/InstallWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "\\.isreposource;\\.git;\\.gitignore;\\.gitattributes;INSTALL-dev;cmake/FindCUDA\\.cmake;cmake/FindCUDA;ccache")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/root/gromacs-mo833a;/;/root/gromacs-mo833a/build_release/docs/man;docs/man;/root/gromacs-mo833a/build_release/src/programs/completion;src/programs/completion")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/root/gromacs-mo833a/build_release/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "gromacs-2020.2-dev")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/root/gromacs-mo833a/build_release/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
